### ISSUE TITLE
Indiana Jones and the Last Crusade - The Action Game (1989)

### ISSUE THREAD

**Issue by Burrito78** [TotalDOSCollection/TDCbugs#12]
File:
Indiana Jones and the Last Crusade- The Action Game [a1] (1989)(Lucasfilm Games) [Action].zip

Issue:
@aaronsgiles thinks this is probably a hacked version.

![Bildschirmfoto 2024-06-24 um 14 05 42](https://github.com/TotalDOSCollection/TDCbugs/assets/61995128/ce04d8ad-fe2b-41e6-8250-5c227dc24e33)

**Comment by TotalDOSCollection** [comment]
INDY.RLE has changes that starts and ends on a sector (512byte) boundary, so that file is very likely just corrupt from a floppy read.

`Deleted:Indiana Jones and the Last Crusade- The Action Game [a1] (1989)(Lucasfilm Games) [Action].zip-->corrupt.`

Related:
`
Added:Indiana Jones and the Last Crusade- The Action Game v1.0 (1989)(Lucasfilm Games) [IMA][720k].zip
Renamed:Indiana Jones and the Last Crusade- The Action Game (1989)(Lucasfilm Games) [Action][!].zip-->Indiana Jones and the Last Crusade- The Action Game v1.0 (1989)(Lucasfilm Games) [Action].zip
Added:Indiana Jones and the Last Crusade- The Action Game v1.0 (1989)(Lucasfilm Games) [IMA][360k].zip
Replaced:Indiana Jones and the Last Crusade- The Action Game (1989)(Lucasfilm Games) [Action].zip-->Indiana Jones and the Last Crusade- The Action Game v1.0 [a1] (1989)(Lucasfilm Games) [Action].zip
Added:Indiana Jones and the Last Crusade- The Action Game v1.1 (1989)(Lucasfilm Games) [IMA][720k].zip
Added:Indiana Jones and the Last Crusade- The Action Game v1.1 [a1] (1989)(Lucasfilm Games) [Action].zip
Added:Indiana Jones and the Last Crusade- The Action Game v1.0 (1989)(U.S. Gold Ltd., Lucasfilm Games LLC) [IMA][720k][cp].zip
Added:Indiana Jones and the Last Crusade- The Action Game v1.0 (1989)(U.S. Gold Ltd., Lucasfilm Games LLC) [Action].zip
Added:Indiana Jones and the Last Crusade- The Action Game v1.0 (1989)(U.S. Gold Ltd., Lucasfilm Games LLC) [IMA][360k][cp].zip

`
