### ISSUE TITLE
Masterblazer (1991)

### ISSUE THREAD

**Issue by Burrito78** [TotalDOSCollection/TDCbugs#14]
File:
Masterblazer v0.99 Gamma release (1991)(LucasArts) [Action, Racing - Driving, Sports].zip

Issue:
Copy protection is hacked out

![Bildschirmfoto 2024-06-24 um 16 45 35](https://github.com/TotalDOSCollection/TDCbugs/assets/61995128/f1f8a906-b126-424f-88f6-7777af06d8ae)

**Comment by TotalDOSCollection** [comment]
That version appears to have come from a compilation, possibly 
Gamebox- 50 Spiele (Installer) (De) (1996)(Softgold Computerspiele GmbH) [Compilation].zip

It has CDSON.EXE and an install.bat file which are also found on that compilation.
which would mean it was officially or semi-officially released with copy protection removed.  It probably could/should go away completely since it's available already in another format.

The main exe file was decompressed and cracked.  I've documented the crack changes in the wiki.

This one:
Masterblazer (1991)(LucasArts) [Action, Racing - Driving, Sports].zip
Reports the same v0.99 gamma release but now has 1991 timestamps, so this one might be closer to the real floppy release - still investigating.

We also happen to have a known good dump of this title, but I believe it is the top shots re-release as the timestamps on it were 1992 and it was released on 2x720k (see moby)

So I renamed it (do I/should I add Lucasgames LLC to the publisher list here)? 
Crock was able to crack it without decompression.
```
Renamed:Masterblazer (1991)(Rainbow Arts Software GmbH) [kfx][720k][!].zip-->Masterblazer (1992)(Softgold Computerspiele GmbH, Softgold Computerspiele GmbH, Topshots) [kfx][720k][!].zip
Renamed:Masterblazer (1991)(Rainbow Arts Software GmbH) [IMA][720k][!].zip-->Masterblazer (1992)(Softgold Computerspiele GmbH, Softgold Computerspiele GmbH, Topshots) [IMA][720k][!].zip
Replaced:Masterblazer (1991)(LucasArts) [Action, Racing - Driving, Sports].zip-->Masterblazer (1992)(Softgold Computerspiele GmbH, Softgold Computerspiele GmbH, Topshots) [Action, Racing - Driving, Sports][!].zip

```

Now that I've written all that, I see that tgod 3166 is also 2x720 and is even more 1992 than the [!] copy above, so I don't actually know which one of these is topshots yet.  More research is needed here.

**Comment by TotalDOSCollection** [comment]
ok, I reversed my above situation.
I believe tgod 3166 is the top shots release.  It already cracked upon installation.

So we have two copies in TDC today:
the [!] copy, has MASTER.EX_ (uncracked) and MASTER.EXE cracked via crock2  This copy is compressed with LZ91.
THe top shots release, which only has MASTER.EXE and is cracked differently than what crock2 does.  This copy is not compressed.

Copies taken from compilations are no longer in TDC.
