### ISSUE TITLE
Baal (1989)

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#3]
base (TDC/rename)
 - 3x525DD - TGOD#1880/gruby/random old scrape ; digitoxin
 -- IHC munge - MBR is really "IBM  3.3"
 --- file transition randomness looks legit
 -- digitoxin has it "fixed"?
 - Baal (1988)(Psygnosis Limited) [Action]
 -- this has the BAAL.DOC from a scene release (BAAL-[1,2,3] 1989-11-29)
 -- matches ; rename 1989 Psyclapse ; remove DOC

a1 (new)
 - 2x35DD - TGOD#3014/TDC/gruby/digitoxin/flyers80
 -- Baal (1989)(Psyclapse) [IMA][720k][!]
 -- Baal (1989)(Psyclapse) [kfx][720k][!]
 --- confirmed kfx=ima
 - INSTALL.BAT and labels only difference from above
 - either add this as ! or a1

Tandy (TDC/rename)
 - 3x525DD - gruby
 -- IHC munge - MBR is really "IBM  3.3"
 --- file transition randomness looks legit
 - Baal (Tandy) (1988)(Psygnosis Limited) [Action]
 -- matches
 - add IMA ; rename 1989 Psyclapse

alternate scene release BAAL[1,2,3] 06-16-90
 - not found

**Comment by TotalDOSCollection** [comment]
```
Renamed:Baal (1989)(Psyclapse) [kfx][720k][!].zip-->Baal (1989)(Psygnosis Limited) [kfx][720k][!].zip
Renamed:Baal (1989)(Psyclapse) [IMA][720k][!].zip-->Baal (1989)(Psygnosis Limited) [IMA][720k][!].zip
Replaced:Baal (1988)(Psygnosis Limited) [Action].zip-->Baal (1989)(Psygnosis Limited) [Action][!].zip
Added:Baal (1989)(Psygnosis Limited) [IMA][360k].zip
Added:Baal [a1] (1989)(Psygnosis Limited) [Action].zip
Added:Baal (Tandy) (1989)(Psygnosis Limited) [IMA][360k].zip
Replaced:Baal (Tandy) (1988)(Psygnosis Limited) [Action].zip-->Baal (Tandy) (1989)(Psygnosis Limited) [Action].zip
```
* Baal (1989)(Psygnosis Limited) [Action][!].zip - sourced from known good kfx/ima set, 2x720k.  Use BAAL.EXE and not START.EXE to run it, even though START seems like the more obvious choice.  
* Baal [a1] (1989)(Psygnosis Limited) [Action].zip - sourced from 3x360k IMA, tgod.  Disks have no volume labels and there's a deleted save game on disk 2 which could be interesting if intact.
* Baal (1989)(Psygnosis Limited) [IMA][360k].zip - this is tgod 1880.  Modified.  Has mangled OEM IDs as well as a deleted save game file on disk 2 (that could be original?)
* Baal (Tandy) (1988)(Psygnosis Limited) [IMA][360k].zip - sourced from gruby. Modified.  Has mangled OEM IDs as well as a deleted save game file on disk 2 (which looks original since the other set of disks has one too.  This set of disks should possibly go inside the zip of the PC release as it appears to have been released as a 6 disk set and not standalone.

Added cheats and manuals too.  Also can't find the scene release.  May have already been processed.
